version: "3.4"
services:
  mysql:
    image: mysql:5
    container_name: mysql
    restart: always
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/init-files:/docker-entrypoint-initdb.d
    env_file:
      - ./back/.env
    ports:
      - "0.0.0.0:3366:3306" 
    #network_mode: "host"
  frontend:
    image: lacerdaguilherme/front:latest
    container_name: frontend
    restart: always
    #depends_on:
    #  - backend
    env_file:
      - ./front/.env
    ports:
      - "80:80"      
  backend:
    image: lacerdaguilherme/back:latest
    container_name: backend
    restart: always
    #depends_on:
      #- mysql
    env_file:
      - ./back/.env
    ports:
      - "1234:1234"