---

- hosts: localhost

  tasks:
  - name: "Build de imagem Backend"
    command: docker build -t back {{ playbook_dir }}back/
    become: true

  - name: "Aplicando tag latest na imagem back"
    shell: docker tag back:latest lacerdaguilherme/back:latest
    become: true

  - name: "Push na imagem back para repositorio"
    shell: docker push lacerdaguilherme/back:latest
    become: true

  - name: "Build de imagem frontend"
    shell:  docker build -t front /home/guilherme/workspace/devmuch-sre-challange/front/ 
    become: true

  - name: "Aplicando tag latest na imagem front"
    shell: docker tag front:latest lacerdaguilherme/front:latest
    become: true

  - name: "Push na imagem front para repositorio"
    shell: docker push lacerdaguilherme/front:latest  
    become: true